# Configuration for Tealium rule plugin
# Proxy Host if calling within the corp network with a gateway like Mcafee gateway.
proxyHost: ${tealium.proxyHost:}
# Proxy Port if proxy host is used. default value will be 443 which means HTTPS.
proxyPort: ${tealium.proxyPort:}
# If HTTP2 is used to connect to the tealium site.
enableHttp2: ${tealium.enableHttp2:false}

# A list of applied request path prefixes and authentication mappings, other requests will skip this handler.
# Each item will have properties to help get the token from the tealium access token service. For each API
# or request path prefix, you need to define an item in the list for authentication. This will allow the object
# to be created and cache the token per path prefix.
pathPrefixAuths: ${tealium.pathPrefixAuths:}
# format with JSON for config server
#  [{"pathPrefix":"/event","tokenTtl":180,"tokenUrl":"https://platform.tealiumapis.com/v3/auth/accounts/networknt/profiles/main","username":"steve.hu@networknt.com","password":"password}]

# format with YAML for readability
#  - pathPrefix: /event
#    tokenTtl: 180
#    tokenUrl: https://platform.tealiumapis.com/v3/auth/accounts/networknt/profiles/main
#    username: steve.hu@networknt.com
#    password: password
