# Configuration for ePAM rule plugin
# Certificate file name. The private key alias is the filename without the .jks extension.
certFilename: ${epam.certFilename:epam.jks}
# Certificate file password
certPassword: ${epam.certPassword:password}
# Proxy Host if calling within the corp network with a gateway like Mcafee gateway.
proxyHost: ${epam.proxyHost:}
# Proxy Port if proxy host is used. default value will be 443 which means HTTPS.
proxyPort: ${epam.proxyPort:}
# If HTTP2 is used to connect to the epam site.
enableHttp2: ${epam.enableHttp2:false}
# Client Id for the ePAM token access.
clientId: ${epam.clientId:}
# Token scope for the ePAM token access.
scope: ${epam.scope:}


# A list of applied request path prefixes and authentication mappings, other requests will skip this handler.
# Each item will have properties to help get the token from the ePAM access token service. For each API
# or request path prefix, you need to define an item in the list for authentication. This will allow the object
# to be created and cache the token per path prefix.
pathPrefixAuths: ${epam.pathPrefixAuths:}
# format with JSON for config server
#  [{"pathPrefix":"/epam","clientId":"networknt-uat01","scope":"ePAM","tokenTtl":180,"tokenUrl":"https://epamws-test.ssgx.com/auth"}]

# format with YAML for readability
#  - pathPrefix: /epam
#    clientId: networknt-uat01
#    scope: ePAM
#    tokenTtl: 180
#    tokenUrl: https://epamws-test.ssgx.com/auth
