proxyHost: ${token-transformer.proxyHost:}
proxyPort: ${token-transformer.proxyPort:}
enableHttp2: ${token-transformer.enableHttp2:false}
moduleMasks: ${token-transformer.moduleMasks:}
tokenSchemas: ${token-transformer.tokenSchemas:}
#*-------------------------------------------------*#
#*---------< mras two-way SSL example >------------*#
#*-------------------------------------------------*#
#  mrasSSL:
#    sharedVariables:
#      username: "my-basic-username"
#      password: "my-basic-password"
#      tokenTtl: 300000
#    request:
#      cacheHttpClient: true
#      cacheSSLContext: false
#      url: "https://test.mras.com/services/oauth2/token"
#      type: application/x-www-form-urlencoded
#      sslContextSchema:
#        tlsVersion: TLSv1.2
#        trustStore:
#          name: client.truststore
#          password: password
#        keyStore:
#          name: keyStoreName.pk12
#          password: password
#          keyPass: password
#      headers:
#        Content-Type: application/x-www-form-urlencoded
#        Authorization: "BASIC <encoded_credentials>"
#      body:
#        grant_type: client_credentials
#
#    source:
#      body:
#        - source: access_token
#          destination: "!ref(sharedVariables.accessToken)"
#        - source: scope
#          destination: "!ref(sharedVariables.scope)"
#
#    update:
#      direction: REQUEST
#      headers:
#        Authorization: "Bearer !ref(sharedVariables.accessToken)"

#*-------------------------------------------------*#
#*----------< mras microsoft example >-------------*#
#*-------------------------------------------------*#
#  mrasMicrosoft:
#    sharedVariables:
#      clientId: "my-microsoft-client-id"
#      clientSecret: "my-microsoft-client-secret"
#    request:
#      cacheHttpClient: true
#      url: "https://test.mras.com/services/oauth2/token"
#      type: application/x-www-form-urlencoded
#      headers:
#        Content-Type: application/x-www-form-urlencoded
#      body:
#        grant_type: "client_credentials"
#        resource: "9bcadce-3312-4c2b-9a5d-0e90e8b92c67"
#        client_id: "!ref(sharedVariables.clientId)"
#        client_secret: "!ref(sharedVariables.clientSecret)"
#
#    source:
#      body:
#        - source: access_token
#          destination: "!ref(sharedVariables.accessToken)"
#        - source: expires_in
#          destination: "!ref(sharedVariables.tokenTtl)"
#
#    update:
#      direction: REQUEST
#      headers:
#        Authorization: "Bearer !ref(sharedVariables.accessToken)"

#*-------------------------------------------------*#
#*-------------< lifeware example >----------------*#
#*-------------------------------------------------*#
#  lifeware:
#    sharedVariables:
#      clientId: "my-id"
#      clientSecret: "abc-123"
#    request:
#      cacheHttpClient: true
#      url: "https://networknttest.asp.lifeware.lu/api/v0/token"
#      type: application/json
#      headers:
#        Content-Type: application/json
#        Accept: application/json
#      body:
#        client_id: "!ref(sharedVariables.clientId)"
#        client_secret: "!ref(sharedVariables.clientSecret)"
#    source:
#      body:
#        - source: access_token
#          destination: "!ref(sharedVariables.accessToken)"
#    update:
#      direction: REQUEST
#      headers:
#        Authorization: "Bearer !ref(sharedVariables.accessToken)"

#*-------------------------------------------------*#
#*------------< Salesforce example >---------------*#
#*-------------------------------------------------*#
#  salesforce:
#    sharedVariables:
#      grantType: urn:ietf:params:oauth:grant-type:jwt-bearer
#      tokenTtl: 60000
#    request:
#      cacheHttpClient: false
#      url: https://test.salesforce.com/services/oauth2/token
#      type: "application/x-www-form-urlencoded"
#      jwtSchema:
#        jwtTtl: 300
#        keyStore:
#          name: apigatewayuat.pfx
#          password: password01
#          alias: apigatewayuat
#          keyPass: password01
#        algorithm: SHA256withRSA
#        jwtHeader:
#          staticFields:
#            alg: RS256
#        jwtBody:
#          staticFields:
#            iss: 3MVG9S11UK8FGR879789g3O.vJebzXvWgAE211Z9KX_7vmKt6k300-2913g_AdsTWtzBTLI232Y1w21kw2HANBfU9jTTJF9h5mL.2tJdY142hyaPW
#            sub: apiuser.conquestintegration@networknt.sit
#            aud: https://test.salesforce.com
#          expiryFields:
#            - exp
#      headers:
#        Content-Type: application/x-www-form-urlencoded
#      body:
#        grant_type: "!ref(sharedVariables.grantType)"
#
#        # accessToken is populated by configured jwtSchema
#        assertion: "!ref(sharedVariables.accessToken)"
#    source:
#      body:
#        - source: access_token
#          destination: "!ref(sharedVariables.accessToken)"
#    update:
#      direction: REQUEST
#      headers:
#        Authorization: "Bearer !ref(sharedVariables.accessToken)"
