proxyHost: ${token-transformer.proxyHost:}

# Proxy Port if proxy host is used. default value will be 443 which means HTTPS.
proxyPort: ${token-transformer.proxyPort:}

# If HTTP2 is used to connect to the specified auth token source.
enableHttp2: ${token-transformer.enableHttp2:false}

# A list of applied request path prefixes and authentication mappings, other requests will skip this handler.
# Each item will have properties to help get the token from the tealium access token service. For each API
# or request path prefix, you need to define an item in the list for authentication. This will allow the object
# to be created and cache the token per path prefix.
pathPrefixAuths: ${token-transformer.pathPrefixAuths:}

# Masks used in module registry
moduleMasks: ${token-transformer.moduleMasks:}