# Configuration for ServiceNow rule plugin
# Proxy Host if calling within the corp network with a gateway like Mcafee gateway.
proxyHost: ${snow.proxyHost:}
# Proxy Port if proxy host is used. default value will be 443 which means HTTPS.
proxyPort: ${snow.proxyPort:}
# If HTTP2 is used to connect to the ServiceNow site.
enableHttp2: ${snow.enableHttp2:false}

# A list of applied request path prefixes and authentication mappings, other requests will skip this handler.
# Each item will have properties to help get the token from the ServiceNow access token endpoint. For each API
# or request path prefix, you need to define an item in the list for authentication. This will allow the object
# to be created and cache the token per path prefix.
pathPrefixAuths: ${snow.pathPrefixAuths:}
# format with JSON for config server
#  [{"pathPrefix":"/snow","tokenTtl":180,"tokenUrl":"https://networknt.service-now.com/oauth_token.do","username":"steve.hu@networknt.com","password":"password","client_id":"b8f2ea8302988f6","client_secret":"lgpass","grant_type":"password"}]

# format with YAML for readability
#  - pathPrefix: /snow
#    tokenTtl: 180
#    tokenUrl: https://networknt.service-now.com/oauth_token.do
#    username: steve.hu@networknt.com
#    password: password
#    client_id: b8f2ea8302988f6
#    client_secret: lgpass
#    grant_type: password
